[package]
name = "restructed"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = ["builder"]
openapi = ["dep:poem-openapi"]
builder = ["dep:typed-builder"]
welds = ["dep:welds"]

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["parsing"] }


# Supported Crates
poem-openapi = { version = "3.0", features = [
    "uuid",
    "chrono",
], optional = true }

typed-builder = { version = "0.18.0", optional = true }
welds = { version = "0.2.1", default-features = false, optional = true}
